model_options:
  test_size: 0.2
  random_state: 12345

travel_insurance:
  target_col: 'claim'
  encoding:
    one_hot_cols: 
      - 'agency_type'
      - 'distribution_channel'
      - 'gender'
    catboost:
      cols:
        - 'agency'
        - 'destination'
        - 'product_name'
  scaler:
    std:
      - 'net_sales'
      - 'commision'
      - 'duration'
